# Generated by Django 5.0.dev20230802093507 on 2023-08-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("test_eighteen", "0001_initial"),
        ("test_seventeen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test_seventeen.author"
            ),
        ),
        migrations.AddField(
            model_name="bookgenre",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="test_eighteen.book"
            ),
        ),
        migrations.AddField(
            model_name="genre",
            name="m2m_field",
            field=models.ManyToManyField(to="test_eighteen.book"),
        ),
        migrations.AddField(
            model_name="bookgenre",
            name="genre",
            field=models.ManyToManyField(to="test_eighteen.genre"),
        ),
    ]
