# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_eighteen", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
    ]
