# Generated by Django 5.0.dev20230806144525 on 2023-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_eighteen", "0003_alter_book_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="unrelatedmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "test_seventeen_unrelatedmodel",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
    ]
