# Generated by Django 5.0.dev20230713133532 on 2023-07-13 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("test_four", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_four.group",
                    ),
                ),
                ("m2m", models.ManyToManyField(to="test_four.person")),
            ],
        ),
    ]
