# Generated by Django 5.0.dev20230816142938 on 2023-08-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_a", "0001_initial"),
        ("app_b", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="books_published",
            field=models.ManyToManyField(to="app_b.genre"),
        ),
    ]
