# Generated by Django 5.0.dev20230816145718 on 2023-08-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_a", "0002_initial"),
        ("app_b", "0002_publisher_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"managed": False},
        ),
    ]
