# Generated by Django 5.0.dev20230816145718 on 2023-08-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_a", "0003_alter_book_options_alter_publisher_options"),
        ("app_b", "0003_alter_publisher_options_alter_bookgenre_genre_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="book",
        ),
        migrations.DeleteModel(
            name="publisher",
        ),
    ]
