# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_thirteen", "0002_book"),
        ("test_twelve", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="publisher",
            name="books_published",
            field=models.ManyToManyField(to="test_thirteen.book"),
        ),
    ]
