# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_thirteen", "0003_alter_book_options_genre_m2m_field_and_more"),
        ("test_twelve", "0002_alter_book_options_alter_publisher_books_published"),
    ]

    operations = [
        migrations.DeleteModel(
            name="book",
        ),
    ]
