# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_eleven", "0002_comment"),
        ("test_ten", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="comment_m2m",
            field=models.ManyToManyField(to="test_eleven.comment"),
        ),
    ]
