# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_eight", "0001_initial"),
        ("test_nine", "0002_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="publisher",
            name="books_published",
            field=models.ManyToManyField(to="test_nine.book"),
        ),
    ]
