# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_thirteen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_twelve.author",
                    ),
                ),
            ],
            options={
                "db_table": "test_twelve_book",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
    ]
