# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_fifteen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="testfourteenmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "test_fourteen_TestFourteenModel",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
    ]
