# Generated by Django 5.0.dev20230806144525 on 2023-08-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_eighteen", "0004_unrelatedmodel_remove_book_author"),
        ("test_seventeen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "test_eighteen_book",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="unrelatedmodel",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="publisher",
            name="books_published",
            field=models.ManyToManyField(to="test_seventeen.book"),
        ),
    ]
