# Generated by Django 5.0.dev20230806144525 on 2023-08-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_eighteen", "0005_alter_bookgenre_book_alter_genre_m2m_field_and_more"),
        ("test_seventeen", "0002_book_alter_unrelatedmodel_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="unrelatedmodel",
        ),
    ]
