# Generated by Django 5.0.dev20230806144525 on 2023-08-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_eighteen", "0004_alter_bookgenre_options_remove_book_author_and_more"),
        ("test_seventeen", "0002_book_bookgenre_alter_publisher_books_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookgenre",
            options={},
        ),
    ]
