# Generated by Django 5.0.dev20230714050639 on 2023-07-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyRelatedModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_one.mymodel",
                    ),
                ),
                (
                    "field_m2m",
                    models.ManyToManyField(related_name="many", to="test_one.mymodel"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mymodel",
            name="fkfk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="test_one.myrelatedmodels",
            ),
        ),
    ]
