# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_one", "0001_initial"),
        ("test_two", "0002_mymodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mymodel",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="myrelatedmodels",
            name="field_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test_two.mymodel"
            ),
        ),
        migrations.AlterField(
            model_name="myrelatedmodels",
            name="field_m2m",
            field=models.ManyToManyField(related_name="many", to="test_two.mymodel"),
        ),
    ]
