# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_one",
            "0002_alter_mymodel_options_alter_myrelatedmodels_field_fk_and_more",
        ),
        ("test_two", "0003_alter_mymodel_options_alter_myothermodel_field_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="mymodel",
        ),
    ]
