# Generated by Django 5.0.dev20230811145154 on 2023-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_twentyone", "0001_initial"),
        ("test_twentytwo", "0002_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="author",
            name="book_m2m",
            field=models.ManyToManyField(
                related_name="book_m2m", to="test_twentytwo.book"
            ),
        ),
    ]
