# Generated by Django 5.0.dev20230811145154 on 2023-08-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_twentyone", "0002_alter_book_options_alter_author_book_m2m"),
        ("test_twentytwo", "0003_alter_book_options_alter_product_book_fk"),
    ]

    operations = [
        migrations.DeleteModel(
            name="book",
        ),
    ]
