# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_five", "0003_alter_membership_options"),
        ("test_four", "0002_alter_membership_options_alter_group_members"),
    ]

    operations = [
        migrations.DeleteModel(
            name="membership",
        ),
    ]
