# Generated by Django 5.0.dev20230806144525 on 2023-08-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_nineteen", "0002_initial"),
        ("test_twenty", "0002_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"managed": False},
        ),
    ]
