# Generated by Django 5.0.dev20230806144525 on 2023-08-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_twenty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="test_nineteen.post",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_twenty.author",
                    ),
                ),
                ("publication_date", models.DateTimeField()),
            ],
            options={
                "db_table": "test_nineteen_article",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
            bases=("test_nineteen.post",),
        ),
    ]
