# Generated by Django 5.0.dev20230806144525 on 2023-08-11 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_nineteen", "0003_alter_article_options"),
        ("test_twenty", "0002_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.AlterField(
            model_name="reader",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test_twenty.article"
            ),
        ),
    ]
