# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_fifteen", "0002_testfourteenmodel"),
        ("test_fourteen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testfourteenmodel",
            options={"managed": False},
        ),
    ]
