# Generated by Django 5.0.dev20230715161641 on 2023-07-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "custom_db_table",
            },
        ),
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_six.mainmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MyModelM2M",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_m2m",
                    models.ManyToManyField(
                        through="test_six.MyModel", to="test_six.mainmodel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mymodel",
            name="m2m_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="test_six.mymodelm2m"
            ),
        ),
    ]
