# Generated by Django 5.0.dev20230806144525 on 2023-08-08 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_seven", "0001_initial"),
        ("test_six", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mymodel",
            options={"managed": False},
        ),
        migrations.AddField(
            model_name="mainmodel",
            name="m2m_field",
            field=models.ManyToManyField(to="test_six.mymodelm2m"),
        ),
        migrations.AddField(
            model_name="mymodelm2m",
            name="field_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="test_seven.mymodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mymodelm2m",
            name="field_m2m",
            field=models.ManyToManyField(
                through="test_seven.MyModel", to="test_six.mainmodel"
            ),
        ),
    ]
