# Generated by Django 5.0.dev20230806144525 on 2023-08-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_seven", "0002_initial"),
        ("test_six", "0002_alter_mymodel_options_mainmodel_m2m_field_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="mymodel",
        ),
    ]
