# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_eleven", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("m2m", models.ManyToManyField(to="test_eleven.mymodel")),
            ],
            options={
                "db_table": "test_ten_comment",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
    ]
