# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_eleven", "0002_comment"),
        ("test_ten", "0002_alter_comment_options_alter_newsarticle_comment_m2m"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={},
        ),
    ]
