# Generated by Django 5.0.dev20230714050639 on 2023-07-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("test_one", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyOtherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_one.mymodel",
                    ),
                ),
            ],
        ),
    ]
