# Generated by Django 5.0.dev20230806144525 on 2023-08-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_two", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="mymodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fkfk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_one.myrelatedmodels",
                    ),
                ),
            ],
            options={
                "db_table": "test_one_mymodel",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
    ]
