# Generated by Django 5.0.dev20230816145718 on 2023-08-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_b", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("books_published", models.ManyToManyField(to="app_b.genre")),
            ],
            options={
                "db_table": "app_a_publisher",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_a.author"
                    ),
                ),
            ],
            options={
                "db_table": "app_a_book",
                "indexes": [],
                "constraints": [],
                "managed": False,
            },
        ),
    ]
