# Generated by Django 5.0.dev20230816145718 on 2023-08-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_a", "0003_alter_book_options_alter_publisher_options"),
        ("app_b", "0002_publisher_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publisher",
            options={},
        ),
        migrations.AlterField(
            model_name="bookgenre",
            name="genre",
            field=models.ManyToManyField(to="app_b.publisher"),
        ),
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
        migrations.AlterField(
            model_name="bookgenre",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app_b.book"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="m2m_field",
            field=models.ManyToManyField(to="app_b.book"),
        ),
    ]
